// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thnmzqgpidkhgnqawagf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRobm16cWdwaWRraGducWF3YWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODM2NDEsImV4cCI6MjA3MzU1OTY0MX0.8G28JFKRn2hg8S7NXD7nHeh30eNVm3LpxcgPGmpTynU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});